# Generated by Django 5.0.3 on 2024-03-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VehicleFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="images")),
                ("show_on_gallery", models.BooleanField(default=False)),
                ("featured", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_name", models.CharField(max_length=100)),
                ("full_name", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("CARS", "Autos"),
                            ("PICKUPS", "Pickups y Comerciales"),
                            ("SUVS", "Suvs y Crossovers"),
                        ],
                        default="CARS",
                        max_length=100,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("features", models.ManyToManyField(to="vehicles.vehiclefeature")),
            ],
        ),
    ]
