# Generated by Django 5.0.3 on 2024-03-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="order_weight",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="published",
            field=models.BooleanField(default=True),
        ),
    ]
