# Generated by Django 5.0.3 on 2024-03-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0002_vehicle_order_weight_vehicle_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="vehicle_images"),
        ),
        migrations.AlterField(
            model_name="vehiclefeature",
            name="image",
            field=models.ImageField(upload_to="feature_images"),
        ),
    ]
